"""
Localization Manager - Handles multi-language support for the TUR system.
"""

TRANSLATIONS = {
    "EN": {
        "AUDIO": "AUDIO",
        "VIDEO": "VIDEO",
        "GAMEPLAY": "GAMEPLAY",
        "INPUT": "INPUT",
        "SINGLE PLAYER": "SINGLE PLAYER",
        "STORY CAMPAIGN": "STORY CAMPAIGN",
        "MULTIPLAYER": "MULTIPLAYER",
        "OPTIONS": "OPTIONS",
        "CREDITS": "CREDITS",
        "SYSTEM UPDATE": "SYSTEM UPDATE",
        "CONTROLLER CONFIG": "CONTROLLER CONFIG",
        "SUPPORT": "SUPPORT",
        "EXIT": "EXIT",
        "VOLUME": "MASTER VOLUME",
        "MUSIC_VOLUME": "MUSIC VOLUME",
        "SFX_VOLUME": "SFX VOLUME",
        "SPEED": "SCROLL SPEED",
        "UPSCROLL": "UPSCROLL MODE",
        "OFFSET": "AUDIO OFFSET",
        "THEME": "UI THEME",
        "RESOLUTION": "RESOLUTION",
        "FULLSCREEN": "FULLSCREEN",
        "V-SYNC": "VERTICAL SYNC",
        "CRT FILTER": "CRT SCANLINES",
        "HIT SOUNDS": "HIT SFX",
        "VISUAL FX": "VISUAL FX",
        "SCREEN SHAKE": "SCREEN SHAKE",
        "NOTE STYLE": "NOTE STYLE",
        "SHOW FPS": "PERFORMANCE HUD",
        "BG DIM": "BACKGROUND DIM",
        "KEYBINDS": "KEYBOARD MAPPING",
        "DEADZONE": "STICK DEADZONE",
        "RE-GEN MAPS": "RE-GENERATE BEATMAPS",
        "LANGUAGE": "SYSTEM LANGUAGE",
        "VIM BINDINGS": "VIM COMMANDS",
        "BACK": "BACK TO MENU",
        "DANGER: RE-GENERATE": "DANGER: RE-GENERATE",
        "This will OVERWRITE existing maps": "This will OVERWRITE existing maps",
        "with new patterns. Are you sure?": "with new patterns. Are you sure?",
        "[Y] CONFIRM   [N] CANCEL": "[Y] CONFIRM   [N] CANCEL",
        "PRESS ENTER": "PRESS ENTER",
        "ACTIVE": "ACTIVE",
        "[ENTER] Skip": "[ENTER] Skip"
    },
    "ES": {
        "AUDIO": "AUDIO",
        "VIDEO": "VÍDEO",
        "GAMEPLAY": "JUEGO",
        "INPUT": "CONTROLES",
        "SINGLE PLAYER": "UN JUGADOR",
        "STORY CAMPAIGN": "CAMPAÑA DE HISTORIA",
        "MULTIPLAYER": "MULTIJUGADOR",
        "OPTIONS": "OPCIONES",
        "CREDITS": "CRÉDITOS",
        "SYSTEM UPDATE": "ACTUALIZACIÓN",
        "CONTROLLER CONFIG": "CONFIG. MANDO",
        "SUPPORT": "SOPORTE",
        "EXIT": "SALIR",
        "VOLUME": "VOLUMEN MAESTRO",
        "MUSIC_VOLUME": "VOLUMEN MÚSICA",
        "SFX_VOLUME": "VOLUMEN EFECTOS",
        "SPEED": "VELOCIDAD SCROLL",
        "UPSCROLL": "MODO UPSCROLL",
        "OFFSET": "COMPENSACIÓN",
        "THEME": "TEMA UI",
        "RESOLUTION": "RESOLUCIÓN",
        "FULLSCREEN": "PANTALLA COMPLETA",
        "V-SYNC": "SINCRONIZACIÓN VERT.",
        "CRT FILTER": "FILTRO CRT",
        "HIT SOUNDS": "SFX DE GOLPE",
        "VISUAL FX": "EFECTOS VISUALES",
        "SCREEN SHAKE": "SACUDIDA PANTALLA",
        "NOTE STYLE": "ESTILO DE NOTA",
        "SHOW FPS": "HUD RENDIMIENTO",
        "BG DIM": "ATENUACIÓN BG",
        "KEYBINDS": "MAPEO TECLADO",
        "DEADZONE": "ZONA MUERTA",
        "RE-GEN MAPS": "REGENERAR BEATMAPS",
        "LANGUAGE": "IDIOMA SISTEMA",
        "VIM BINDINGS": "COMANDOS VIM",
        "BACK": "VOLVER AL MENÚ",
        "DANGER: RE-GENERATE": "PELIGRO: REGENERAR",
        "This will OVERWRITE existing maps": "Esto SOBRESCRIBIRÁ los mapas existentes",
        "with new patterns. Are you sure?": "con nuevos patrones. ¿Estás seguro?",
        "[Y] CONFIRM   [N] CANCEL": "[Y] CONFIRMAR [N] CANCELAR",
        "PRESS ENTER": "PULSAR ENTER",
        "ACTIVE": "ACTIVO",
        "[ENTER] Skip": "[ENTER] Saltar"
    },
    "FR": {
        "AUDIO": "AUDIO",
        "VIDEO": "VIDÉO",
        "GAMEPLAY": "JEU",
        "INPUT": "MANETTE",
        "SINGLE PLAYER": "SOLO",
        "STORY CAMPAIGN": "CAMPAGNE",
        "MULTIPLAYER": "MULTIJOUEUR",
        "OPTIONS": "OPTIONS",
        "CREDITS": "CRÉDITS",
        "SYSTEM UPDATE": "MISE À JOUR",
        "CONTROLLER CONFIG": "CONFIG. MANETTE",
        "SUPPORT": "SUPPORT",
        "EXIT": "QUITTER",
        "VOLUME": "VOLUME GÉNÉRAL",
        "MUSIC_VOLUME": "VOLUME MUSIQUE",
        "SFX_VOLUME": "VOLUME EFFETS",
        "SPEED": "VITESSE DÉFILEMENT",
        "UPSCROLL": "MODE UPSCROLL",
        "OFFSET": "DÉCALAGE AUDIO",
        "THEME": "THÈME UI",
        "RESOLUTION": "RÉSOLUTION",
        "FULLSCREEN": "PLEIN ÉCRAN",
        "V-SYNC": "SYNCHRO VERTICALE",
        "CRT FILTER": "FILTRE CRT",
        "HIT SOUNDS": "SFX DE FRAPPE",
        "VISUAL FX": "EFFETS VISUELS",
        "SCREEN SHAKE": "SECOUSSE ÉCRAN",
        "NOTE STYLE": "STYLE DE NOTE",
        "SHOW FPS": "HUD PERF",
        "BG DIM": "OPACITÉ FOND",
        "KEYBINDS": "TOUCHES CLAVIER",
        "DEADZONE": "ZONE MORTE",
        "RE-GEN MAPS": "RÉGÉNÉRER BEATMAPS",
        "LANGUAGE": "LANGUE SYSTÈME",
        "VIM BINDINGS": "COMMANDES VIM",
        "BACK": "RETOUR AU MENU",
        "DANGER: RE-GENERATE": "DANGER : RÉGÉNÉRER",
        "This will OVERWRITE existing maps": "Cela ÉCRASERA les cartes existantes",
        "with new patterns. Are you sure?": "avec de nouveaux motifs. Continuer ?",
        "[Y] CONFIRM   [N] CANCEL": "[Y] CONFIRMER  [N] ANNULER",
        "PRESS ENTER": "APPUYER SUR ENTRÉE",
        "ACTIVE": "ACTIF",
        "[ENTER] Skip": "[ENTRÉE] Passer"
    },
    "JP": {
        "AUDIO": "オーディオ",
        "VIDEO": "ビデオ",
        "GAMEPLAY": "ゲームプレイ",
        "INPUT": "操作設定",
        "SINGLE PLAYER": "シングルプレイヤー",
        "STORY CAMPAIGN": "ストーリーモード",
        "MULTIPLAYER": "マルチプレイヤー",
        "OPTIONS": "オプション",
        "CREDITS": "クレジット",
        "SYSTEM UPDATE": "システム更新",
        "CONTROLLER CONFIG": "コントローラー設定",
        "SUPPORT": "サポート",
        "EXIT": "終了",
        "VOLUME": "マスター音量",
        "MUSIC_VOLUME": "音楽音量",
        "SFX_VOLUME": "効果音音量",
        "SPEED": "スクロール速度",
        "UPSCROLL": "アップスクロール",
        "OFFSET": "判定オフセット",
        "THEME": "UIテーマ",
        "RESOLUTION": "解像度",
        "FULLSCREEN": "フルスクリーン",
        "V-SYNC": "垂直同期",
        "CRT FILTER": "CRTフィルター",
        "HIT SOUNDS": "ヒット効果音",
        "VISUAL FX": "視覚効果",
        "SCREEN SHAKE": "画面の揺れ",
        "NOTE STYLE": "ノーツスタイル",
        "SHOW FPS": "パフォーマンス表示",
        "BG DIM": "背景の暗さ",
        "KEYBINDS": "キーバインド",
        "DEADZONE": "デッドゾーン",
        "RE-GEN MAPS": "譜面再生成",
        "LANGUAGE": "表示言語",
        "VIM BINDINGS": "VIMコマンド",
        "BACK": "メニューに戻る",
        "DANGER: RE-GENERATE": "警告: マップ再生成",
        "This will OVERWRITE existing maps": "既存のマップを上書きします",
        "with new patterns. Are you sure?": "よろしいですか？",
        "[Y] CONFIRM   [N] CANCEL": "[Y] 確定      [N] 取消",
        "PRESS ENTER": "ENTERを押す",
        "ACTIVE": "実行中",
        "[ENTER] Skip": "[ENTER] スキップ"
    }
}

def get_text(game, key):
    lang = game.settings.get("language") or "EN"
    bundle = TRANSLATIONS.get(lang, TRANSLATIONS["EN"])
    return bundle.get(key, key)
